### ISSUE TITLE
xtest的Dockerfile在构建中报错

### ISSUE THREAD

**Issue by jamesz2011** [x-utest/xtest-docker#1]
![image](https://user-images.githubusercontent.com/16397200/38162563-aa64a3f0-3515-11e8-84c1-ac38bfe7cf1f.png)

-------------

【ps】在Ubuntu 16.04.0 下Docker build错误！！！

**Comment by ityoung** [comment]
您好，请问再次构建也会报这样的错吗？

**Comment by ityoung** [comment]
如果一直不行，可否尝试编辑Dockerfile，在`# front-end`节，`COPY`命令之后重启一行，添加如下命令试试：
```
RUN npm i -g npm && \
grep -ir “sha512 .......... OA==” ~/.npm
```

ps：引号内的`sha512 ... `这部分来自您的第二条报错信息 `npm ERR!`，一直复制到报错信息的 **小数点** 之前为止。

还有疑问可以添加 qq 19101269，谢谢！

**Comment by jamesz2011** [comment]
![image](https://user-images.githubusercontent.com/16397200/38163010-399d53d8-351f-11e8-85af-1890e3e2300d.png)
【ps】docker run -p 8009:8009 -p 8099:8099 -v /opt/xtest-docker/xtest-data/data/db -it xtest:1.0后报上图的错

**Comment by ityoung** [comment]
构建docker镜像完成后，需要有初始化mongodb的操作，否则会报连接mongo失败相关的错哈。镜像构建成功了是吗？有其他问题可以另外提个issue，这个issue我关闭了哈，谢谢反馈！
