### ISSUE TITLE
使用的markdowm文档有点小错误：下面是小错误的出错点和排错解决方法：

### ISSUE THREAD

**Issue by jamesz2011** [x-utest/xtest-docker#2]
![使用的markdowm文档有点小错误](https://user-images.githubusercontent.com/16397200/38163177-259a2386-3522-11e8-8eec-c7e9e87c4040.png)

**Comment by ityoung** [comment]
已修改，谢谢反馈！

有任何问题可以加群讨论哈，x-utest测试开发平台QQ群：547955053

ps：我看到过不同的创建volume的方式，一种是你提到的需要 --name参数，另一种是不需要。不知道是否和docker版本有关，我是安装最新的docker版本，未加--name参数可以创建volume。不过文档中我还是添加了该参数，回头我会好好查一查相关说明学习一下，再次谢谢！
